import assert from "node:assert/strict";
import { SUBCLASS_TREES, normalizeTreeRanks, normalizeBerserkLoadout, treeBlockReason, applyTreeStats } from "../shared/src/classes/skillTrees.js";
import { createInitialBattleState } from "../server/src/modules/combat/battleRoom.js";
import { createDungeonEquipment } from "../shared/src/loot/dungeonLoot.js";
import { createBerserkAxe } from "../shared/src/equipment/berserkWeapons.js";
import { canEquipItem, canonicalEquipment } from "../shared/src/equipment/equipmentRules.js";
import { getEquipmentById } from "../server/src/modules/equipment/equipmentService.js";
import { adaptSubclassWeaponDrops } from "../shared/src/equipment/assassinWeapons.js";
import { applyBattleAction, applyEnemyTurn, tickHeroDamage } from "../shared/src/combat/combatEngine.js";
import { getHeroSkills, getSkillBlockReason, getSkill } from "../shared/src/combat/classSkills.js";
import { advanceBattleAtb } from "../shared/src/combat/atb.js";
import { applySubclassStats } from "../shared/src/classes/subclasses.js";
import { createStatsForLevel } from "../shared/src/combat/classStats.js";
import { loadSubclassProgress, useSubclassBook } from "../client/src/progression/subclassClient.js";
import { loadInventory, ensureBerserkEquipment, equipItem } from "../client/src/inventory/inventoryClient.js";
import { investTreePoint, setBerserkSkillSlot, resetTreePoints } from "../client/src/progression/skillTreeClient.js";
import { startDemoBattle, subscribeDemoBattle, performDemoAction, useDemoConsumable } from "../client/src/demo/demoBattle.js";
import type { BattleState } from "../shared/src/types/combat.js";
import { emptyBerserkState } from "../shared/src/combat/berserkCombat.js";

const tree = SUBCLASS_TREES.berserker.filter(node => !node.attributeBranch);
assert.equal(tree.length, 18);
assert.equal(tree.filter(node => node.skill).length, 9);
assert.equal(tree.filter(node => node.final).length, 3);
assert.ok(tree.every(node => node.maxRank === 1));
const nonfinal = Object.fromEntries(tree.filter(node => !node.final).map(node => [node.id, 1]));
const full = { ...nonfinal, "berserker-executor": 1 };
assert.deepEqual(normalizeTreeRanks("berserker", 17, full), full);
assert.deepEqual(normalizeTreeRanks("berserker", 1, full), {});
assert.deepEqual(normalizeTreeRanks("berserker", 100, { "berserker-executor": 1 }), {});
assert.deepEqual(normalizeTreeRanks("berserker", 100, { "berserker-brutal": 2 }), {});
assert.deepEqual(normalizeTreeRanks("berserker", 100, { "berserker-foundation": 5 }), {});
assert.equal(treeBlockReason("berserker", 2, {}, tree[0]!), null);
assert.ok(treeBlockReason("berserker", 100, {}, tree.find(node => node.id === "berserker-voracious")!));
const twoFinals = normalizeTreeRanks("berserker", 100, { ...full, "berserker-avatar": 1, "berserker-titan": 1 });
assert.equal(tree.filter(node => node.final && twoFinals[node.id]).length, 1);
assert.ok(treeBlockReason("berserker", 100, full, tree.find(node => node.id === "berserker-avatar")!));
assert.equal(normalizeBerserkLoadout(100, full).length, 4);
assert.deepEqual(normalizeBerserkLoadout(100, full, ["berserker-brutal", "berserker-brutal", "warrior-cleave", "unknown", "berserker-executor"]), ["berserker-brutal", "", "", ""]);
assert.deepEqual(normalizeBerserkLoadout(100, full, []), []);
const weapon = createDungeonEquipment("guerreiro", "weapon", 20, "epic");
const shield = createDungeonEquipment("guerreiro", "shield", 20, "epic");
const axe = createBerserkAxe(weapon);
assert.deepEqual(axe.stats, weapon.stats);
assert.equal(axe.rarity, weapon.rarity);
assert.ok(canEquipItem(axe, "guerreiro", 20, "berserker"));
assert.equal(canEquipItem(axe, "guerreiro", 19, "berserker"), false);
assert.equal(canEquipItem(axe, "guerreiro", 20, "paladin"), false);
assert.equal(canEquipItem(weapon, "guerreiro", 20, "berserker"), false);
assert.equal(canEquipItem(shield, "guerreiro", 20, "berserker"), false);
assert.deepEqual(getEquipmentById(axe.id), axe);
assert.deepEqual(canonicalEquipment({ ...axe, stats: { attack: 99999 } }), axe);
assert.deepEqual(adaptSubclassWeaponDrops([{ item: weapon, quantity: 2 }], "berserker"), [{ item: axe, quantity: 2 }]);
const base = createStatsForLevel("guerreiro", 20);
assert.equal(applySubclassStats(base, "berserker").criticalDamage, base.criticalDamage);
assert.equal(applyTreeStats(base, "berserker", 100, full).maxHp, base.maxHp + Math.floor(base.maxHp * .12));
const storage = new Map<string, string>();
Object.assign(globalThis, { localStorage: { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => storage.set(key, value) }, window: { setInterval: () => 1, clearInterval() {} } });
storage.set("classeHeroi", "guerreiro"); storage.set("drakoriaProgresso", '{"nivel":20}');
storage.set("drakoriaSubclassProgress", '{"activeSubclass":"berserker","books":{"berserker":2},"treeRanks":{"berserker-foundation":5}}');
assert.deepEqual(loadSubclassProgress().treeRanks, {});
assert.equal(loadSubclassProgress().books.berserker, 2);
assert.equal(loadSubclassProgress().berserkTreeVersion, 2);
storage.set("drakoriaInventario", JSON.stringify({ items: [{ item: weapon, quantity: 1 }, { item: shield, quantity: 1 }], equipped: { weapon: weapon.id, shield: shield.id } }));
let inventory = loadInventory();
assert.equal(inventory.equipped.weapon, axe.id);
assert.equal(inventory.equipped.shield, undefined);
assert.equal(inventory.items.length, 3);
ensureBerserkEquipment(); ensureBerserkEquipment();
assert.equal(loadInventory().items.length, 3);
assert.equal(equipItem(shield.id).equipped.shield, undefined);
assert.equal(equipItem(weapon.id).equipped.weapon, axe.id);
assert.equal(investTreePoint("berserker-brutal"), null);
assert.equal(investTreePoint("berserker-instinct"), null);
assert.equal(investTreePoint("berserker-warcry"), null);
assert.equal(setBerserkSkillSlot(3, "berserker-warcry"), "Habilidade já equipada");
assert.equal(setBerserkSkillSlot(1, ""), null);
assert.equal(setBerserkSkillSlot(3, "berserker-warcry"), null);
assert.equal(loadSubclassProgress().equippedSkills?.[3], "berserker-warcry");
assert.ok(setBerserkSkillSlot(0, "berserker-executor"));
resetTreePoints(); assert.deepEqual(loadSubclassProgress().treeRanks, {}); assert.deepEqual(loadSubclassProgress().equippedSkills, []);
storage.set("drakoriaSubclassProgress", '{"books":{"berserker":1}}');
assert.equal(useSubclassBook("berserker", "guerreiro").used, true);
assert.equal(loadInventory().items.length, 3);

function battle(final = "executor", slots?: string[]): BattleState {
  const ranks = { ...nonfinal, [`berserker-${final}`]: 1 };
  const state = createInitialBattleState("guerreiro", "goblin-normal-lvl-1", [axe, shield], 100, {}, "berserker", "Heroi", ranks, slots);
  state.hero.stats.hp = 100; state.hero.stats.maxHp = 1000; state.hero.stats.attack = 100; state.hero.stats.criticalChance = 0; state.hero.stats.defense = 0; state.hero.stats.dodgeChance = 0;
  state.hero.fury = 100;
  state.enemy.stats.hp = state.enemy.stats.maxHp = 10000; state.enemy.stats.defense = 0; state.enemy.stats.dodgeChance = 0; state.enemy.stats.criticalChance = 0; state.enemy.stats.attack = 100; state.enemy.stats.magicPower = 0;
  state.turnOwnerId = state.hero.id;
  return state;
}
const rng = Math.random; Math.random = () => .99;
try {
  // All nine actives resolve with their canonical costs and never consume mana.
  for (const node of tree.filter(node => node.skill)) {
    const final = node.final ? node.id.slice(10) : "executor";
    const state = battle(final, [node.id]);
    const before = structuredClone(state);
    const result = applyBattleAction(state, { type: "USE_SKILL", skillId: node.skill!.id });
    assert.notEqual(result, state, node.id); assert.deepEqual(state, before);
    assert.equal(result.hero.stats.mana, state.hero.stats.mana);
    assert.equal(result.hero.skillCooldowns?.[node.skill!.id], node.skill!.cooldown);
    assert.equal(result.lastEvent?.skillId, node.id);
    if (node.skill!.hits) assert.ok((result.lastEvent?.damage ?? 0) > 0);
    if (node.skill!.furyCost) assert.equal(result.hero.fury, 100 - node.skill!.furyCost);
  }
  const state = battle("executor", ["berserker-brutal"]);
  state.hero.fury = 0;
  const hit = applyBattleAction(state, { type: "ATTACK" });
  assert.equal(hit.hero.fury, 9.6); assert.equal(hit.hero.berserk?.stacks, 1);
  const brutal = applyBattleAction(state, { type: "USE_SKILL", skillId: "berserker-brutal" });
  assert.equal(brutal.lastEvent?.damage, 160); assert.equal(brutal.hero.fury, 14.4);
  assert.equal(brutal.hero.stats.hp, 104);
  assert.deepEqual(brutal.enemy.berserkBleed, { damage: 30, turns: 2 });
  let ticking = applyBattleAction({ ...brutal, turnOwnerId: brutal.hero.id }, { type: "DEFEND" });
  assert.equal(ticking.enemy.stats.hp, brutal.enemy.stats.hp - 30);
  assert.equal(ticking.enemy.berserkBleed?.turns, 1);
  ticking = applyBattleAction({ ...ticking, turnOwnerId: ticking.hero.id }, { type: "DEFEND" });
  assert.equal(ticking.enemy.berserkBleed, undefined);
  assert.equal(ticking.hero.skillCooldowns?.["berserker-brutal"], undefined);
  // Overkill cannot inflate healing; bleeding never rolls critical.
  const overkill = battle("executor", ["berserker-brutal"]); overkill.enemy.stats.hp = 10;
  assert.equal(applyBattleAction(overkill, { type: "USE_SKILL", skillId: "berserker-brutal" }).hero.stats.hp, 100);
  const area = battle("executor", ["berserker-devastating"]);
  assert.equal(applyBattleAction(area, { type: "USE_SKILL", skillId: "berserker-devastating" }).hero.stats.hp, 102);
  const blood = battle("executor", ["berserker-blood"]);
  let buff = applyBattleAction(blood, { type: "USE_SKILL", skillId: "berserker-blood" });
  assert.equal(buff.hero.berserk?.blood, 2);
  buff = applyBattleAction({ ...buff, turnOwnerId: buff.hero.id }, { type: "ATTACK" });
  assert.equal(buff.hero.stats.hp, 114);
  const executor = battle("executor", ["berserker-executor"]); executor.enemy.stats.hp = 3000;
  assert.equal(applyBattleAction(executor, { type: "USE_SKILL", skillId: "berserker-executor" }).lastEvent?.damage, 450);
  executor.enemy.stats.hp = 2999;
  assert.equal(applyBattleAction(executor, { type: "USE_SKILL", skillId: "berserker-executor" }).lastEvent?.damage, 675);
  const avatar = battle("avatar", ["berserker-avatar"]);
  let transformed = applyBattleAction(avatar, { type: "USE_SKILL", skillId: "berserker-avatar" });
  assert.equal(transformed.hero.berserk?.avatar, 3);
  const waiting = advanceBattleAtb(transformed);
  assert.ok(waiting.hero.atb > transformed.hero.stats.speed * .5);
  assert.equal(waiting.hero.berserk?.avatar, 3);
  for (let turn = 0; turn < 3; turn++) transformed = applyBattleAction({ ...transformed, turnOwnerId: transformed.hero.id }, { type: "DEFEND" });
  assert.equal(transformed.hero.berserk?.avatar, 0);
  assert.equal(transformed.hero.stats.speed, avatar.hero.stats.speed);
  const charge = battle("executor", ["berserker-charge"]);
  const slowed = applyBattleAction(charge, { type: "USE_SKILL", skillId: "berserker-charge" });
  assert.equal(slowed.enemy.slowedTurns, 1);
  assert.equal(advanceBattleAtb(slowed).enemy.atb, slowed.enemy.stats.speed * .3);
  assert.equal(applyEnemyTurn({ ...slowed, turnOwnerId: slowed.enemy.id }).enemy.slowedTurns, 0);
  const tank = battle("titan", ["berserker-titan"]);
  const titan = applyBattleAction(tank, { type: "USE_SKILL", skillId: "berserker-titan" });
  assert.equal(titan.hero.stats.hp, 250); assert.equal(titan.hero.berserk?.titan, 2);
  const retaliation = applyEnemyTurn({ ...state, turnOwnerId: state.enemy.id });
  assert.equal(retaliation.hero.fury, 4.8);
  assert.equal(retaliation.lastEvent?.damage, 94);
  assert.equal(retaliation.hero.berserk?.retaliation, 2);
  const retaliating = applyBattleAction({ ...retaliation, turnOwnerId: retaliation.hero.id }, { type: "ATTACK" });
  assert.equal(retaliating.lastEvent?.damage, 143); assert.equal(retaliating.hero.berserk?.retaliation, 0);
  const fatal = battle(); fatal.hero.stats.hp = 20;
  let rescued = applyEnemyTurn({ ...fatal, turnOwnerId: fatal.enemy.id });
  assert.equal(rescued.hero.stats.hp, 1); assert.equal(rescued.finished, false);
  assert.equal(rescued.hero.berserk?.refusedDeath, true); assert.equal(rescued.hero.berserk?.deathWard, true);
  const exposed = applyBattleAction({ ...rescued, turnOwnerId: rescued.hero.id }, { type: "DEFEND" });
  rescued = applyEnemyTurn({ ...exposed, turnOwnerId: exposed.enemy.id });
  assert.equal(rescued.finished, true);
  const dot = battle(); dot.hero.stats.hp = 10; dot.hero.ongoingDamage = { name: "Veneno", damage: 100, turns: 3 };
  tickHeroDamage(dot.hero); assert.equal(dot.hero.stats.hp, 1); assert.ok(dot.hero.berserk?.refusedDeath);
  // Dodge gives no Fury/heal/bleed; critical bonus follows the 60-Fury threshold.
  const evaded = battle("executor", ["berserker-brutal"]); evaded.hero.fury = 0; evaded.enemy.stats.dodgeChance = 50;
  Math.random = () => 0;
  const miss = applyBattleAction(evaded, { type: "USE_SKILL", skillId: "berserker-brutal" });
  assert.equal(miss.hero.fury, 0); assert.equal(miss.hero.stats.hp, 100); assert.equal(miss.enemy.berserkBleed, undefined);
  const critTest = battle("executor", ["berserker-brutal"]); Math.random = () => .05;
  critTest.hero.fury = 59;
  assert.equal(applyBattleAction(critTest, { type: "USE_SKILL", skillId: "berserker-brutal" }).lastEvent?.critical, false);
  critTest.hero.fury = 60;
  assert.equal(applyBattleAction(critTest, { type: "USE_SKILL", skillId: "berserker-brutal" }).lastEvent?.critical, true);
  Math.random = () => .99;
  let stacking = battle(); stacking.hero.fury = 99;
  for (let turn = 0; turn < 8; turn++) stacking = applyBattleAction({ ...stacking, turnOwnerId: stacking.hero.id }, { type: "ATTACK" });
  assert.equal(stacking.hero.berserk?.stacks, 5); assert.equal(stacking.hero.fury, 100);
  for (let turn = 0; turn < 2; turn++) stacking = applyBattleAction({ ...stacking, turnOwnerId: stacking.hero.id }, { type: "DEFEND" });
  assert.equal(stacking.hero.berserk?.stacks, 0);
  const refreshed = battle("executor", ["berserker-brutal", "berserker-devastating"]);
  const firstWound = applyBattleAction(refreshed, { type: "USE_SKILL", skillId: "berserker-brutal" });
  const renewedWound = applyBattleAction({ ...firstWound, turnOwnerId: firstWound.hero.id }, { type: "USE_SKILL", skillId: "berserker-devastating" });
  assert.deepEqual(renewedWound.enemy.berserkBleed, { damage: 30, turns: 2 });
  const noAxe = createInitialBattleState("guerreiro", "goblin-normal-lvl-1", [weapon, shield], 100, {}, "berserker", "Heroi", full, ["berserker-brutal"]);
  assert.equal(noAxe.hero.hasTwoHandedAxe, false);
  assert.ok(getSkillBlockReason(noAxe.hero, getSkill("berserker-brutal")!));
  const plain = createInitialBattleState("guerreiro", "goblin-normal-lvl-1", [], 100, {}, "berserker", "Heroi", full);
  assert.deepEqual(noAxe.hero.stats, plain.hero.stats); // Forged setup cannot retain shield/old weapon bonuses.
  const noFury = battle("executor", ["berserker-executor"]); noFury.hero.fury = 0;
  assert.equal(applyBattleAction(noFury, { type: "USE_SKILL", skillId: "berserker-executor" }), noFury);
  assert.equal(applyBattleAction(noFury, { type: "USE_SKILL", skillId: "warrior-cleave" }), noFury);
  assert.equal(applyBattleAction(noFury, { type: "CAST_MAGIC" }), noFury);
  noFury.hero.hasTwoHandedAxe = false;
  assert.ok(getSkillBlockReason(noFury.hero, getSkill("berserker-executor")!));
  const notEquipped = battle("executor", []);
  assert.equal(getHeroSkills(notEquipped.hero).length, 0);
  assert.equal(applyBattleAction(notEquipped, { type: "USE_SKILL", skillId: "berserker-brutal" }), notEquipped);
  // Battle setup parity, saved loadouts, resource reset and immutable consumable actions.
  storage.set("drakoriaProgresso", '{"nivel":100}');
  storage.set("drakoriaSubclassProgress", JSON.stringify({ books: {}, activeSubclass: "berserker", berserkTreeVersion: 2, treeRanks: full, equippedSkills: ["berserker-brutal"] }));
  storage.set("drakoriaConsumables", JSON.stringify({healthPotion:2,manaPotion:0,restorativePotion:0}));
  let demo!: BattleState; subscribeDemoBattle(state => { demo = state; }); startDemoBattle("guerreiro", "goblin-normal-lvl-1", 100);
  const server = createInitialBattleState("guerreiro", "goblin-normal-lvl-1", [axe], 100, { hp: demo.hero.stats.hp, mana: demo.hero.stats.mana }, "berserker", "Heroi", full, ["berserker-brutal"]);
  assert.deepEqual(demo.hero.stats, server.hero.stats); assert.deepEqual(demo.hero.equippedSkills, server.hero.equippedSkills);
  assert.equal(demo.hero.fury, 0); assert.deepEqual(demo.hero.berserk, emptyBerserkState());
  demo.turnOwnerId = demo.hero.id; demo.enemy.stats.hp = demo.enemy.stats.maxHp = 10000;
  performDemoAction({ type: "USE_SKILL", skillId: "berserker-brutal" });
  const previous = demo; const snapshot = structuredClone(previous);
  demo.turnOwnerId = demo.hero.id; demo.hero.stats.hp -= 50;
  const potionSnapshot = structuredClone(demo);
  assert.equal(useDemoConsumable("healthPotion"), true);
  assert.deepEqual(previous, potionSnapshot);
  assert.equal(demo.hero.skillCooldowns?.["berserker-brutal"], 1);
  assert.equal(demo.enemy.berserkBleed?.turns, 1);
  startDemoBattle("guerreiro", "goblin-normal-lvl-1", 100); assert.equal(demo.hero.fury, 0);
} finally { Math.random = rng; }
console.log("Berserk: all 18 nodes/nine actives, root/gates/finals, four slots, axe/shield migration, Fury, DOT, healing, buffs, execution, retaliation, death prevention and demo/server parity passed.");
