import assert from "node:assert/strict";
import vm from "node:vm";
import { readFileSync } from "node:fs";
import { equipItem, unequipSlot, loadInventory, getEquippedItems } from "../client/src/inventory/inventoryClient.js";
import { STARTER_LOOT_ITEMS } from "../shared/src/loot/lootTables.js";

const saved = new Map<string, string>();
Object.defineProperty(globalThis, "localStorage", { value: { getItem: (key: string) => saved.get(key) ?? null, setItem: (key: string, value: string) => saved.set(key, value) }, configurable: true });
saved.set("classeHeroi", "guerreiro");
saved.set("drakoriaProgresso", '{"nivel":25}');
const axe = STARTER_LOOT_ITEMS["orc-iron-axe"]!;
const sword = STARTER_LOOT_ITEMS["orc-warlord-sword"]!;
saved.set("drakoriaInventario", JSON.stringify({ items: [{ item: axe, quantity: 2 }, { item: sword, quantity: 1 }], equipped: {} }));
const windowStub: { getBackpackEntries?: (inventory: ReturnType<typeof loadInventory>) => ReturnType<typeof loadInventory>["items"] } = {};
vm.runInNewContext(readFileSync("js/inventory-backpack.js", "utf8"), { window: windowStub });
const backpack = () => windowStub.getBackpackEntries!(loadInventory());
equipItem(axe.id);
assert.equal(backpack().find(entry => entry.item.id === axe.id)?.quantity, 1);
assert.equal(getEquippedItems()[0]?.id, axe.id);
equipItem(sword.id);
assert.equal(backpack().some(entry => entry.item.id === sword.id), false);
assert.equal(backpack().find(entry => entry.item.id === axe.id)?.quantity, 2);
unequipSlot("weapon");
assert.equal(backpack().find(entry => entry.item.id === sword.id)?.quantity, 1);
assert.equal(loadInventory().items.reduce((sum, entry) => sum + entry.quantity, 0), 3);
assert.equal(getEquippedItems().length, 0);
const panel = { innerHTML: "", classList: { remove() {} } };
const uiWindow = { addEventListener() {}, progressoDrakoria: { carregarProgresso: () => ({ nivel: 25 }), adicionarRecompensa() {} } };
const context = vm.createContext({ window: uiWindow, localStorage: globalThis.localStorage, document: { addEventListener() {}, getElementById: () => panel } });
vm.runInContext(readFileSync("js/inventory-backpack.js", "utf8"), context);
vm.runInContext(readFileSync("js/status-inventory-ux.js", "utf8"), context);
vm.runInContext(`window.equiparItemInventario('${sword.id}')`, context);
// Comparison tooltip mentions the equipped item without adding a backpack copy.
const backpackHtml = panel.innerHTML.split('<div class="inventory-grid">')[1]!
  .replace(/<div class="paper-tooltip inventory-comparison-source">[\s\S]*?<\/div>/g, "");
assert.ok(!backpackHtml.includes(sword.name));
assert.ok(panel.innerHTML.split('<h3 class="section-title">Itens')[0]!.includes(sword.name));
vm.runInContext('window.desequiparSlotInventario("weapon")', context);
assert.ok(panel.innerHTML.split('<div class="inventory-grid">')[1]!.includes(sword.name));
vm.runInContext(`window.equiparItemInventario('${axe.id}'); window.venderItemInventario('${axe.id}')`, context);
assert.equal(loadInventory().items.find(entry => entry.item.id === axe.id)?.quantity, 1);
vm.runInContext(`window.venderItemInventario('${axe.id}')`, context);
assert.equal(loadInventory().items.find(entry => entry.item.id === axe.id)?.quantity, 1);
assert.equal(getEquippedItems()[0]?.id, axe.id);
console.log("inventoryBackpack.test.ts: equipped copy, duplicate copies, swap, unequip and saved ownership passed");
