import assert from "node:assert/strict";
import { SUBCLASS_IDS, SUBCLASS_DEFINITIONS } from "../shared/src/classes/subclasses.js";
import { useSubclassBook, resetTestCharacterSubclass, loadSubclassProgress } from "../client/src/progression/subclassClient.js";
import { getCurrentHeroStats, getSubclassPreviewStats } from "../client/src/progression/heroStats.js";
import { loadInventory } from "../client/src/inventory/inventoryClient.js";
import { getTestCharacterEquipment } from "../shared/src/testing/testCharacter.js";
import { createInitialBattleState } from "../server/src/modules/combat/battleRoom.js";
import { getHeroSkills } from "../shared/src/combat/classSkills.js";
import { getHeroGifs } from "../client/src/assets/gifs.js";
import { startDemoBattle, subscribeDemoBattle } from "../client/src/demo/demoBattle.js";
import type { BattleState, HeroClass } from "../shared/src/types/combat.js";
const saved = new Map<string,string>();
Object.assign(globalThis,{localStorage:{getItem:(key:string)=>saved.get(key)??null,setItem:(key:string,value:string)=>saved.set(key,value)},window:{setInterval:()=>1,clearInterval(){}}});
saved.set("nomeHeroi","Herói"); saved.set("classeHeroi","guerreiro"); saved.set("drakoriaProgresso",'{"nivel":40,"ouro":321}');
saved.set("drakoriaSubclassProgress",JSON.stringify({books:{elementalist:1},activeSubclass:"paladin",treeRanks:{"paladin-foundation":2}}));
const original=saved.get("drakoriaSubclassProgress");
assert.ok(resetTestCharacterSubclass()); assert.equal(saved.get("drakoriaSubclassProgress"),original);
assert.equal(useSubclassBook("elementalist","guerreiro").used,false);
saved.set("nomeHeroi"," TaIcHoU ");
saved.set("drakoriaHeroVitals",'{"hp":1,"mana":0,"maxHp":500,"maxMana":100}');
assert.equal(resetTestCharacterSubclass(),null);
assert.equal(loadSubclassProgress().books.elementalist,1);
assert.equal(loadSubclassProgress().activeSubclass,undefined);
assert.deepEqual(loadSubclassProgress().treeRanks,{});
assert.equal(resetTestCharacterSubclass(),"Nenhuma subclasse ativa.");
const set = getTestCharacterEquipment("guerreiro");
const weapon=set.find(item=>item.slot === "weapon")!,shield=set.find(item=>item.slot === "shield")!;
saved.set("drakoriaInventario",JSON.stringify({items:[{item:weapon,quantity:1},{item:shield,quantity:1}],equipped:{weapon:weapon.id,shield:shield.id}}));
saved.set("drakoriaSubclassProgress",JSON.stringify({books:Object.fromEntries(SUBCLASS_IDS.map(id=>[id,2]))}));
for(const id of SUBCLASS_IDS){
 const current=saved.get("classeHeroi") as HeroClass;
 const prediction=SUBCLASS_DEFINITIONS[id].baseClass!==current?getSubclassPreviewStats(id):undefined;
 assert.equal(useSubclassBook(id,current).used,true);
 const base=SUBCLASS_DEFINITIONS[id].baseClass;
 assert.equal(saved.get("classeHeroi"),base);
 assert.equal(loadSubclassProgress().activeSubclass,id);
 assert.equal(loadSubclassProgress().books[id],1);
 assert.equal(useSubclassBook(id,base).used,false);
 if(prediction) assert.deepEqual(getCurrentHeroStats(),prediction);
 const inventory=loadInventory();
 assert.ok(inventory.items.some(entry=>entry.item.id===weapon.id&&entry.quantity===1));
 assert.ok(inventory.items.some(entry=>entry.item.id===shield.id&&entry.quantity===1));
 const equipped=inventory.items.filter(entry=>Object.values(inventory.equipped).includes(entry.item.id)).map(entry=>entry.item);
 const server=createInitialBattleState(base,"goblin-normal-lvl-1",equipped,40,{},id,"Taichou",{});
 assert.ok(getHeroSkills(server.hero).every(skill=>skill.heroClass===base));
 assert.ok(getHeroGifs(base,"Masculino",id).padrao.includes("img/"));
 let demo:BattleState|undefined;subscribeDemoBattle(state=>{demo=state;});startDemoBattle(base,"goblin-normal-lvl-1",40);
 assert.deepEqual(demo!.hero.stats,{...server.hero.stats,hp:1,mana:0});
 assert.equal(resetTestCharacterSubclass(),null);
 assert.deepEqual(loadSubclassProgress().treeRanks,{});
 assert.deepEqual(loadSubclassProgress().equippedSkills,undefined);
 assert.equal(loadSubclassProgress().books[id],1);
 assert.equal(JSON.parse(saved.get("drakoriaHeroVitals")!).hp,1);
 assert.equal(JSON.parse(saved.get("drakoriaHeroVitals")!).mana,0);
}
const oldClass=saved.get("classeHeroi");
assert.equal(useSubclassBook("paladin",oldClass as HeroClass).used,true);
assert.equal(resetTestCharacterSubclass(),null);
assert.equal(useSubclassBook("paladin",saved.get("classeHeroi") as HeroClass).used,false);
assert.equal(saved.get("drakoriaProgresso"),'{"nivel":40,"ouro":321}');
console.log("Taichou reset: exclusive permission, all nine books, base adaptation, resources, items, consumption, sprites and demo/server parity passed.");
